name: py-lambda
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@master
    - name: Deploy code to Lambda
      uses: cmsd2/py-lambda-action
    - uses: actions/upload-artifact@v1
      with:
        name: lambda-zip
        path: lambda.zip